dry: true
job_name: asset
run_on_slurm: false
time: 60
task: nlp/seq2seq/multi_ref/asset
dataset: nlp/seq2seq/multi_ref/simplification/asset
gpus: 1
limit_train_samples: 128
seed: 42
run_fit: true
run_predict_after_fit: false
run_validation_after_fit: true
dataset_name: null  # write here the dataset name if you prefer loading it with HF that using local files.
train_file: data/asset.train.json
validation_file: data/asset.validation.json
test_file: data/asset.test.json