model_checkpoint:
  _target_: pytorch_lightning.callbacks.model_checkpoint.ModelCheckpoint
  monitor: ${task.cfg.monitor}
  mode: ${task.cfg.mode}
  verbose: true
  save_top_k: 1
  every_n_epochs: ${trainer.check_val_every_n_epoch}
